interface IData {
  rowSpan?: string;
  colSpan?: string;
  buttonElement: string | React.ReactNode;
  type?: string;
  department: string;
}

interface IItem {
  id: number;
  data: IData;
  color?: string;
}

import Calculator from "./Calculator";

export const info: IItem[] = [
  {
    id: 1,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-2",
      buttonElement: "Notification",
      type: "fixed",
      department: "Admin",
    },
    color: "firstBlock",
  },
  {
    id: 2,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Soda",
      type: "drag",
      department: "Beverages",
    },
    color: "blue",
  },
  {
    id: 3,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Coffee",
      type: "drag",
      department: "Beverages",
    },
    color: "blue",
  },
  {
    id: 4,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Hot Food",
      type: "drag",
      department: "Food",
    },
    color: "blue",
  },
  {
    id: 5,
    data: {
      rowSpan: "row-span-4",
      colSpan: "col-span-3",
      buttonElement: <Calculator />,
      type: "fixed",
      department: "Tools",
    },
    color: "black",
  },
  {
    id: 6,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Alcohol",
      type: "drag",
      department: "Drinks",
    },
    color: "blue",
  },
  {
    id: 7,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Tobacco",
      type: "drag",
      department: "Tobacco",
    },
    color: "blue",
  },
  {
    id: 8,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",

      buttonElement: "blue",
      type: "drag",
      department: "Beverages",
    },
    color: "blue",
  },
  {
    id: 9,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "E-Cig",
      type: "drag",
      department: "Tobacco",
    },
    color: "blue",
  },
  {
    id: 10,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Propane",
      type: "drag",
      department: "Fuel",
    },
    color: "blue",
  },
  {
    id: 11,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Ice Bag",
      type: "drag",
      department: "Frozen Goods",
    },
    color: "blue",
  },
  {
    id: 12,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Snacks",
      type: "drag",
      department: "Food",
    },
    color: "blue",
  },
  {
    id: 13,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Dairy",
      type: "drag",
      department: "Dairy",
    },
    color: "blue",
  },
  {
    id: 14,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Tax",
      type: "drag",
      department: "Finance",
    },
    color: "blue",
  },
  {
    id: 15,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Non-Tax",
      type: "drag",
      department: "Finance",
    },
    color: "blue",
  },
  {
    id: 16,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Lotto",
      type: "drag",
      department: "Entertainment",
    },
    color: "blue",
  },
  {
    id: 17,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Lotto Pay Out",
      type: "drag",
      department: "Finance",
    },
    color: "blue",
  },
  {
    id: 18,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Cash Back Fee",
      type: "drag",
      department: "Finance",
    },
    color: "blue",
  },
  {
    id: 19,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Scratch Off",
      type: "drag",
      department: "Entertainment",
    },
    color: "blue",
  },
  {
    id: 20,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Coupon",
      type: "drag",
      department: "Discounts",
    },
    color: "blue",
  },
  {
    id: 21,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Round Up",
      type: "drag",
      department: "Finance",
    },
    color: "red",
  },
  {
    id: 22,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "EBT",
      type: "drag",
      department: "Finance",
    },
    color: "red",
  },
  {
    id: 23,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Debit",
      type: "drag",
      department: "Finance",
    },
    color: "red",
  },
  {
    id: 24,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Credit",
      type: "drag",
      department: "Finance",
    },
    color: "red",
  },
  {
    id: 25,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "$5",
      type: "drag",
      department: "Sales",
    },
    color: "red",
  },
  {
    id: 26,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "$10",
      type: "drag",
      department: "Sales",
    },
    color: "red",
  },
  {
    id: 27,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "$20",
      type: "drag",
      department: "Finance",
    },
    color: "red",
  },
  {
    id: 28,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "$Cash$",
      type: "drag",
      department: "Finance",
    },
    color: "red",
  },
  {
    id: 29,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "",
      type: "drag",
      department: "",
    },
    color: "white",
  },
  {
    id: 30,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "",
      type: "drag",
      department: "",
    },
    color: "white",
  },
  {
    id: 31,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "",
      type: "drag",
      department: "",
    },
    color: "white",
  },
  {
    id: 32,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "",
      type: "drag",
      department: "",
    },
    color: "white",
  },
  {
    id: 33,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",

      buttonElement: "",
      type: "drag",
      department: "",
    },
    color: "white",
  },
  {
    id: 34,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "",
      type: "drag",
      department: "",
    },
    color: "white",
  },
  {
    id: 35,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "",
      type: "drag",
      department: "",
    },
    color: "white",
  },
  {
    id: 36,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",

      buttonElement: "Misc.",
      type: "drag",
      department: "Miscellaneous",
    },
    color: "white",
  },
  {
    id: 37,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",

      buttonElement: "Void",
      type: "drag",
      department: "Operations",
    },
    color: "red",
  },
  {
    id: 38,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",

      buttonElement: "Discount",
      type: "drag",
      department: "Sales",
    },
    color: "red",
  },
  {
    id: 41,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",

      buttonElement: "No Sale",
      type: "drag",
      department: "Sales",
    },
    color: "red",
  },
  {
    id: 42,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",

      buttonElement: "Suspend",
      type: "drag",
      department: "Operations",
    },
    color: "red",
  },
  {
    id: 43,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",

      buttonElement: "Recall",
      type: "drag",
      department: "Operations",
    },
    color: "red",
  },
  {
    id: 44,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",

      buttonElement: "Safe Drop",
      type: "drag",
      department: "Finance",
    },
    color: "red",
  },
  {
    id: 45,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",

      buttonElement: "Refund",
      type: "drag",
      department: "Finance",
    },
    color: "red",
  },
  {
    id: 46,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",

      buttonElement: "Cancel",
      type: "drag",
      department: "Operations",
    },
    color: "red",
  },
  {
    id: 47,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",

      buttonElement: "",
      type: "drag",
      department: "",
    },
    color: "white",
  },
  {
    id: 48,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "",
      type: "drag",
      department: "",
    },
    color: "white",
  },
  {
    id: 49,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "",
      type: "drag",
      department: "",
    },
    color: "white",
  },
  {
    id: 50,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "",
      type: "drag",
      department: "",
    },
    color: "white",
  },
  {
    id: 51,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Vendor Pay Out",
      type: "drag",
      department: "Finance",
    },
    color: "white",
  },
  {
    id: 52,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-1",
      buttonElement: "Last Card",
      type: "drag",
      department: "Operations",
    },
    color: "white",
  },
  {
    id: 53,
    data: {
      rowSpan: "row-span-1",
      colSpan: "col-span-2",
      buttonElement: "More",
      type: "fixed",
      department: "General",
    },
    color: "lastBlock",
  },
];

// interface IItem {
//   id?: number;
//   rowSpan?: string;
//   colSpan?: string;
//   color?: string;
//   buttonElement: string | React.ReactNode;
//   type?: string;
//   department: string;
// }

// import Calculator from "./Calculator";

// export const info: IItem[] = [
//   {
//     id: 1,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-2",
//     color: "firstBlock",
//     buttonElement: "Notification",
//     type: "fixed",
//     department: "",
//   },
//   {
//     id: 2,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "blue",
//     buttonElement: "Soda",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 3,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "blue",
//     buttonElement: "Coffee",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 4,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "blue",
//     buttonElement: "Hot Food",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 5,
//     rowSpan: "row-span-4",
//     colSpan: "col-span-3",
//     color: "black",
//     buttonElement: <Calculator />,
//     type: "fixed",
//     department: "",
//   },
//   {
//     id: 6,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "blue",
//     buttonElement: "Alcohol",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 7,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "blue",
//     buttonElement: "Tobacco",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 8,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "blue",
//     buttonElement: "blue",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 9,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "blue",
//     buttonElement: "E-Cig",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 10,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "blue",
//     buttonElement: "Propane",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 11,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "blue",
//     buttonElement: "Ice Bag",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 12,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "blue",
//     buttonElement: "Snacks",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 13,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "blue",
//     buttonElement: "Dairy",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 14,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "blue",
//     buttonElement: "Tax",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 15,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "blue",
//     buttonElement: "Non-Tax",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 16,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "blue",
//     buttonElement: "Lotto",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 17,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "blue",
//     buttonElement: "Lotto Pay Out",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 18,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "blue",
//     buttonElement: "Cash Back Fee",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 19,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "blue",
//     buttonElement: "Scratch Off",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 20,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "blue",
//     buttonElement: "Coupon",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 21,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "red",
//     buttonElement: "Round Up",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 22,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "red",
//     buttonElement: "EBT",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 23,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "red",
//     buttonElement: "Debit",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 24,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "red",
//     buttonElement: "Credit",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 25,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "red",
//     buttonElement: "$5",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 26,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "red",
//     buttonElement: "$10",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 27,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "red",
//     buttonElement: "$20",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 28,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "red",
//     buttonElement: "$Cash$",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 29,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "white",
//     buttonElement: "",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 30,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "white",
//     buttonElement: "",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 31,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "white",
//     buttonElement: "",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 32,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "white",
//     buttonElement: "",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 33,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "white",
//     buttonElement: "",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 34,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "white",
//     buttonElement: "",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 35,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "white",
//     buttonElement: "",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 36,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "white",
//     buttonElement: "Misc.",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 37,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "red",
//     buttonElement: "Void",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 38,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "red",
//     buttonElement: "Discount",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 41,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "red",
//     buttonElement: "No Sale",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 42,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "red",
//     buttonElement: "Suspend",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 43,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "red",
//     buttonElement: "Recall",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 44,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "red",
//     buttonElement: "Safe Drop",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 45,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "red",
//     buttonElement: "Refund",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 46,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "red",
//     buttonElement: "Cancel",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 47,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "white",
//     buttonElement: "",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 48,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "white",
//     buttonElement: "",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 49,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "white",
//     buttonElement: "",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 50,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "white",
//     buttonElement: "",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 51,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "white",
//     buttonElement: "Vendor Pay Out",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 52,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-1",
//     color: "white",
//     buttonElement: "Last Card",
//     type: "drag",
//     department: "",
//   },
//   {
//     id: 53,
//     rowSpan: "row-span-1",
//     colSpan: "col-span-2",
//     color: "lastBlock",
//     buttonElement: "More",
//     type: "fixed",
//     department: "",
//   },
// ];
