export type CompanyData = {
  companyNo: string;
  companyName: string;
  address: string;
  zipCode: string;
  countryCode: string;
  // isActive: boolean; // Uncomment if you use the "Status" column
};

export const demoCompanyData: CompanyData[] = [
  {
    companyNo: "001",
    companyName: "Alpha Corp",
    address: "123 Main Street, New York",
    zipCode: "10001",
    countryCode: "US",
    // isActive: true,
  },
  {
    companyNo: "002",
    companyName: "Beta Ltd",
    address: "456 Elm Avenue, London",
    zipCode: "W1A 1AA",
    countryCode: "GB",
    // isActive: false,
  },
  {
    companyNo: "003",
    companyName: "Gamma GmbH",
    address: "789 Berliner Straße, Berlin",
    zipCode: "10115",
    countryCode: "DE",
    // isActive: true,
  },
  {
    companyNo: "004",
    companyName: "Delta Co.",
    address: "101 Maple Rd, Toronto",
    zipCode: "M5H 2N2",
    countryCode: "CA",
    // isActive: false,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
  {
    companyNo: "005",
    companyName: "Epsilon Pvt Ltd",
    address: "55 MG Road, Mumbai",
    zipCode: "400001",
    countryCode: "IN",
    // isActive: true,
  },
];
